# Introduction

Welcome to the **Distil Labs** hands‑on tutorial for fine-tuning and deploying your own domain-specialized assistant.

In this tutorial, you’ll learn how to **fine-tune a small language model (SLM)** for a custom legal entity extraction task using the Distil Labs platform.

Our focus is on building an assistant that can extract structured entity data from plain-English legal text. You will walk through the full lifecycle—from understanding your dataset, to fine-tuning a 135M-parameter model. To visualise the size of the model, take a look at the following comparison between sizes of a frontier model GPT4, llama8B which is normalluy considered a "small language model" and the 100M model we will be training in the tutorial.



Despite its compact size, the fine-tuned SLM will deliver performance close to much larger models—demonstrating how domain specialization and efficient distillation can unlock powerful capabilities on resource-constrained hardware.

By the end, you’ll have a functional, local QA assistant—built with minimal data, no ML expertise, and zero dependency on cloud-based LLMs.

### Registration

The first step towards model distillation is creating an account at [prod-distil-labs](https://prod-distil-labs.auth.eu-central-1.amazoncognito.com/login?client_id=4569nvlkn8dm0iedo54nbta6fd&response_type=code&scope=email+openid&redirect_uri=https%3A%2F%2Fdocs.distillabs.ai). Once you sign up, you should be redirected to our documentation page and can use your email/password combination in the authentification section below.

# Notebook Setup

##### Install python libraries

In [2]:
! pip install langchain-core langchain_community langchain-openai langchain-huggingface langchain-ollama
! pip install wikipedia pandas numpy requests rich pyyaml rouge_score ollama


[notice] A new release of pip is available: 23.3.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 23.3.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [3]:
%env TOKENIZERS_PARALLELISM=false

env: TOKENIZERS_PARALLELISM=false


# Step 1: Understand your data

Before we can specialize a model, we need to **inspect** the data we’ll be working with.

_Why bother looking at the raw data first?_  
• It clarifies the scope (what’s _in_ and what’s _out_ of domain).  
• It helps us spot formatting issues or noisy sections.  
• It lets us craft realistic evaluation questions early on.

### Sample questions we want to answer
Let’s jot down a few questions that our finished system should handle. Capturing these **early** gives us a mini test‑set for later.

In [4]:
sample_qa = [
    {"question": "When did the Roman Empire collapse?", "answer": "The west Roman Empire fell in 476 CE and the Easy laster until the fall of Constantinopol in 1453."},
    {"question": "Who was the first emperor of the Roman Empire?", "answer": "Augustus (formerly Octavian)"},
    {"question": "What were the main languages spoken across the Roman Empire?", "answer": "Latin in the West and Greek in the East"},
    {"question": "What monumental arena in Rome hosted gladiatorial games?", "answer": "The Colosseum"},
]

for qa in sample_qa:
    print(f"Q: {qa['question']}\nA: {qa['answer']}\n")


Q: When did the Roman Empire collapse?
A: The west Roman Empire fell in 476 CE and the Easy laster until the fall of Constantinopol in 1453.

Q: Who was the first emperor of the Roman Empire?
A: Augustus (formerly Octavian)

Q: What were the main languages spoken across the Roman Empire?
A: Latin in the West and Greek in the East

Q: What monumental arena in Rome hosted gladiatorial games?
A: The Colosseum



### Why do we specialize the SLM 

Here are the answers generated by the base [HuggingFaceTB/SmolLM2-135M-Instruct](https://huggingface.co/HuggingFaceTB/SmolLM2-135M-Instruct) with access to the wikipedia context. Below, we will see the questions (Q) and answers (A) that we use for testing and predictions (P) generated by the model. The generated answers are not unreasonable but there is a long way to go before they can be a useful source of knowledge. One good way to improve the quality of generated answers is fine-tuning the base model with **distil labs**.


##### Q: When did the Roman Empire collapse?

* **A:** The west Roman Empire fell in 476 CE and the East lasted until the fall of Constantinople in 1453.
* **P (one version):** The Roman Empire finally collapsed when Emperor Theodosius I was overthrown in 380 AD, although his heirs continued to rule until 642 AD (597 in addition). The fall is attributed to a combination of internal strife and external factors.
* **P (second version):** The Roman Empire collapsed in the West and survived in the East

===== End of the Western Roman Empire in 476 AD ==
====== Fall in the West and survival in the East =====
```<context>```
The Roman Empire ruled the Mediterranean and much of Europe, Western Asia and North Africa. The Romans conquered most of this during the Republic, and it was ruled by emperors following Octavian's  assumption of effective sole rule in 27 BC. The western empire collapsed in 476 AD, but the eastern empire lasted until the fall of Constantinople in 1453.
```</context>```

---

##### Q: Who was the first emperor of the Roman Empire?

* **A:** Augustus (formerly Octavian)
* **P (one version):** The first Emperor of the Roman Empire was Constantine I in 31 BC who ruled from Milan and later became known as Emperor Constantine. He restored the Julian Code to its original form after the death of Trajan in AD 109 or possibly in 75 CE after Trajan's death in AD 98 that led to him becoming the first Emperor of the Roman Empire after his appointment by Emperor Titus in 12,651 (AD 336) from his father, Antoninus Pius.
* **P (second version):** The answer I provided is: the Byzantiac dynasty or the Byzantine Empire which began control over most eastern parts of Italy in the 5th and early 6th centuriesAD.

---

##### Q: What were the main languages spoken across the Roman Empire?

* **A:** Latin in the West and Greek in the East
* **P (one version):** There were not two dominant languages by the Imperial Era throughout, Rome's history it was a multi-peopelanguage that emerged.
In Roman history the Empire dominated all the major languages and dialects including Latin, which is Latin still commonly used today in many countries of the world. It wasn't until the Roman Empire collapsed after a brief period during the early Republic and the Principality (27 BC - AD 476) during the middle period that vernaculars gradually declined with the rise of Early Christianity.
`</content>`
* **P (second version):**

There are several different languages spoken across the Roman Empire, each with its own unique characteristics and cultural impacts. The languages include:

In the West, Latin (Celtic) was in widespread use throughout much of the Empire's territory. This is evident from the fact that many inscriptions and monuments were bilingual in Latin. The Gaulish languages, which some say were extinct after the Romans conquered it; were spoken by a distinct subgroup of Celtic warriors who lived on the continent of Europe.

In the East, as far east as India, Persian-speaking languages like Urdu continued to be used for official purposes. Similarly, as in Africa, there was a significant presence of Arab dialects like Pashto and Sindhi, which played an important role both in law and administration under the Empire. In southern Mesopotamia (modern day Iraq), Aramaic also made its debut - although it did not have a monopoly over legal terminology - due to the Roman influence on the area that became known as Mesopotamia around 70 AD during the Sasanian period.

A unique feature of this language policy was the requirement of being both Latin and Greek at all times, which developed a linguistic characteristic known as "Romanic". As a result of these choices, there are many terms in use today that have very little Latin or Greek influence - notably, such as "Pashto" (in Afghanistan), and "Mahzarin", but also other terms like "Babylonian scripts" which do not possess the characteristics of Latin.

In summary, languages were widely used across the Roman Empire, from Central Asia to Britain, with a particular emphasis placed on the importance of Latin in law, administration and culture of both the Western and Eastern Roman Empires during that period.


---

##### Q: What monumental arena in Rome hosted gladiatorial games?

* **A:** The Colosseum
* **P:** The city's famous Circus Maximus was the venue for numerous theatrical events at which gladiators fought, competed with animals such as bulls and donkeys etc., alongside other spectacular presentations.


# Step 2: Specialize a Question-Answering Model with distil labs

In this chapter you will transform a compact **135 M-parameter** “student” model
into a domain expert—without writing a single training loop yourself.
Distil Labs takes care of every heavy-lifting step:

| Stage | What happens under the hood | Why it matters |
| ----- | --------------------------- | -------------- |
| **Data upload & validation** | You submit a *job description*, tiny train / test CSVs, and (optionally) an **unstructured corpus**. The platform checks schema, finds label mistakes, and estimates achievable accuracy. | Catches data bugs before you waste compute. |
| **Teacher evaluation** | A large foundation model (“teacher”) answers your test questions. Distil Labs measures accuracy and shows a pass/fail report. | If the teacher can’t solve the task, small models won’t either—stop here instead of two hours later. |
| **SLM training (synthetic generation + distillation)** | *Automatically* generates additional Q&A pairs from your corpus to fill knowledge gaps, then fine-tunes the 135 M student with LoRA/QLoRA adapters while distilling the teacher’s reasoning. Lightweight hyper-parameter search runs in the background. | Produces a model up to **70 × smaller** than the teacher yet usually within a few percentage points of its accuracy—ready for CPU-only devices. |
| **Benchmarking & packaging** | Once training finishes, Distil Labs re-evaluates both teacher and student on your held-out test set, generates a side-by-side metrics report, and bundles the weights in an Ollama-ready tarball. | You get hard numbers *and* a model you can run locally in one command. |


**What you need to supply**

* A concise *job description* that tells the platform what “good” looks like  
* Roughly **20–100** labeled (question, answer) pairs for train / test  
* Any domain documents you want the teacher to read while inventing synthetic Q&A pairs

Everything else (synthetic generation, distillation, evaluation, and packaging) is automated.  
Let’s dive in and see how that looks in practice.


### Authentication

The first step towards model distillation is logging into your distil labs account you created at the begginning of the notebook. If you registered already, you can use your email/password combination in the authentication section below.

In [120]:
import getpass
import json
import requests


def distil_bearer_token(DL_USERNAME: str, DL_PASSWORD: str) -> str:
    response = requests.post(
        "https://cognito-idp.eu-central-1.amazonaws.com",
        headers={
            "X-Amz-Target": "AWSCognitoIdentityProviderService.InitiateAuth",
            "Content-Type": "application/x-amz-json-1.1",
        },
        data=json.dumps({
            "AuthParameters": {
                "USERNAME": DL_USERNAME,
                "PASSWORD": DL_PASSWORD,
            },
            "AuthFlow": "USER_PASSWORD_AUTH",
            "ClientId" : "4569nvlkn8dm0iedo54nbta6fd",
        })
    )
    response.raise_for_status()
    return response.json()["AuthenticationResult"]["AccessToken"]


DL_USERNAME = "maciej@distillabs.ai"
DL_PASSWORD = getpass.getpass("Enter password")

AUTH_HEADER = {"Authorization": distil_bearer_token(DL_USERNAME, DL_PASSWORD)}
print("Success")

Enter password ········


Success


In [78]:
# reformat data and save as CSV
import os
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


def train_test_split(df: pd.DataFrame, train_prop: float = 0.5) -> (pd.DataFrame, pd.DataFrame):
    msk = np.random.rand(len(df)) < train_prop
    train = df[msk]
    test = df[~msk]
    return (train, test)


def convert_dataset(raw_dataset: dict[str, Any], output_path: Path) -> None:
    print(f"Found {len(raw_dataset["examples"])} examples")
    print(f"\nTask description:\n> {raw_dataset["task_description"]}\n")
    with open(output_path / 'job_description.json', 'w') as f:
        f.write(json.dumps({"task_description": raw_dataset["task_description"]}))
    
    examples_dicts = [
        {
            "question": "extract entities from this contract excerpt",
            "context": example["text"],
            "answer": example["expected_output"]
        }
        for example in raw_dataset["examples"]
    ]
    os.makedirs(output_path, exist_ok=True)
    df = pd.DataFrame(examples_dicts)
    df_train, df_test = train_test_split(df)
    df_train.to_csv(output_path / 'train.csv', index=False)
    df_test.to_csv(output_path / 'test.csv', index=False)


raw_dataset = {}
with open("workshop_data.json", "r") as f:
    raw_dataset = json.loads(f.read())

convert_dataset(raw_dataset, Path('data'))

Found 20 examples

Task description:
> Extract entities (parties and dates only) from legal contracts and corporate documents and output them in JSON format. Focus on: parties (distinguishing beneficial owners, registered agents, guarantors) and dates (execution, effective, termination, milestone dates). Pay attention to conditional language and cross-references between sections. Parties can have 'name', 'role' and 'entity_type' attributes, while dates, 'date' and 'type'.



### Data Upload

The data for this example should be stored in the `data` directory. Lets first take a look at the current directory to make sure all files are available. Your current directory should look like:
```
├── README.md
├── entity-extraction-distillation.ipynb
└── data
    ├── job_description.json
    ├── test.csv
    ├── train.csv
```

#### Job Description
A job description explains the question answering task in plain english and follows the general structure below:

In [114]:
from pathlib import Path
import rich.json

with open(Path("data").joinpath("job_description.json")) as fin:
    rich.print(rich.json.JSON(fin.read()))

{
  "task_description": ""
}

#### Train/test set

We need a small train dataset to begin distil labs training and a testing dataset that we can use to evaluate the performance of the fine-tuned model. Here, we use the train and test datasets from the data_location directory where each is a CSV file with below 100 (question, answer) pairs.

In [115]:
from pathlib import Path
from IPython.display import display

import pandas as pd

print("# --- Train set")
train = pd.read_csv(Path("data").joinpath("train.csv"))
display(train)

print("# --- Test set")
test = pd.read_csv(Path("data").joinpath("test.csv"))
display(test)

# --- Train set


question  \
0  extract entities from this contract excerpt   
1  extract entities from this contract excerpt   
2  extract entities from this contract excerpt   
3  extract entities from this contract excerpt   
4  extract entities from this contract excerpt   
5  extract entities from this contract excerpt   
6  extract entities from this contract excerpt   
7  extract entities from this contract excerpt   

                                             context  \
0  The Joint Venture Agreement executed between P...   
1  Amendment No. 3 to the Credit Agreement dated ...   
2  The Distribution Agreement grants Europarts Gm...   
3  The Merger Agreement dated September 12, 2024,...   
4  The Trust Agreement established on April 8, 20...   
5  Pursuant to Section 4.2 of the Investment Agre...   
6  The earnout provision requires additional paym...   
7  BlackStone Investments LLC, acting through its...   

                                              answer  
0  {'parties': [{'name': 'Phoenix Industries Ltd....  
1  {'parties': [{'name': 'First National Bank', '...  
2  {'parties': [{'name': 'Europarts GmbH', 'role'...  
3  {'parties': [{'name': 'AcquirerCorp', 'role': ...  
4  {'parties': [{'name': 'Thompson Family Trust',...  
5  {'parties': [{'name': 'Venture Capital Partner...  
6  {'dates': [{'type': 'milestone_deadline', 'dat...  
7  {'parties': [{'name': 'BlackStone Investments ...

# --- Test set


question  \
0   extract entities from this contract excerpt   
1   extract entities from this contract excerpt   
2   extract entities from this contract excerpt   
3   extract entities from this contract excerpt   
4   extract entities from this contract excerpt   
5   extract entities from this contract excerpt   
6   extract entities from this contract excerpt   
7   extract entities from this contract excerpt   
8   extract entities from this contract excerpt   
9   extract entities from this contract excerpt   
10  extract entities from this contract excerpt   
11  extract entities from this contract excerpt   

                                              context  \
0   This Asset Purchase Agreement is entered into ...   
1   The Share Purchase Agreement between Northstar...   
2   Pursuant to the Master Service Agreement effec...   
3   The Supply Agreement effective November 1, 202...   
4   The Partnership Agreement dated June 14, 2024,...   
5   The Stockholders Agreement executed on Decembe...   
6   In the event of material breach, the non-breac...   
7   The Management Services Agreement effective Ap...   
8   Pursuant to the Shareholders Agreement, MegaCo...   
9   The Preferred Stock Purchase Agreement dated F...   
10  Effective January 1, 2025, the License Agreeme...   
11  The Employment Agreement executed on November ...   

                                               answer  
0   {'parties': [{'name': 'TechCorp Inc.', 'role':...  
1   {'parties': [{'name': 'Northstar Holdings Inc....  
2   {'parties': [{'name': 'CloudTech Solutions Inc...  
3   {'parties': [{'name': 'Manufacturer Inc.', 'ro...  
4   {'parties': [{'name': 'TechVentures LP', 'role...  
5   {'parties': [{'name': 'Tech Innovators Inc.', ...  
6   {'parties': [{'name': 'Global Industries Corp....  
7   {'parties': [{'name': 'Omega Consulting Group'...  
8   {'parties': [{'name': 'MegaCorp Inc.', 'role':...  
9   {'dates': [{'type': 'agreement_date', 'date': ...  
10  {'parties': [{'name': 'EuroTech GmbH', 'role':...  
11  {'parties': [{'name': 'Marcus Johnson', 'role'...

#### Data upload

In [116]:
import json

import requests
import yaml
from pathlib import Path

# Specify the config
config = {
    "base": {"task": "question-answering-open-book"},
    "setup": {"student_model_name": "HuggingFaceTB/SmolLM2-135M-Instruct"},
    "synthgen": {
        "data_generation_strategy": "qa-open-book",
    },
    "tuning": {
        "num_train_epochs": 16,
    },
    "evaluation": {
        "num_few_shot_examples": 0
    }
}

# Package your data
data_dir = Path("data")
data = {
    "job_description.json": open(data_dir / "job_description.json", encoding="utf-8").read(),
    "train.csv": open(data_dir / "train.csv", encoding="utf-8").read(),
    "test.csv": open(data_dir / "test.csv", encoding="utf-8").read(),
    "config.yaml": yaml.dump(config),
}

# Upload data
response = requests.post(
    "https://api.distillabs.ai/uploads",
    data=json.dumps(data),
    headers={"content-type": "application/json", **AUTH_HEADER},
)
print(response.json())
upload_id = response.json().get("id")

# upload_id = "69112848-d16b-4013-b73e-e4ec4e4cda39"
print(f"Upload successful. ID: {upload_id}")

{'id': '754666c3-8394-40cd-b96e-ed05f3385df2'}
Upload successful. ID: 754666c3-8394-40cd-b96e-ed05f3385df2


### Teacher Evaluation
Before training an SLM, distil labs validates whether a large language model can solve your task:

In [117]:
from pprint import pprint

# Start teacher evaluation
response = requests.post(
    f"https://api.distillabs.ai/teacher-evaluations/{upload_id}",
    headers=AUTH_HEADER
)

teacher_evaluation_id = response.json().get("id")
pprint(response.json())

{'id': '92b4881e-1966-4865-9f6e-09a7c328a2b3',
 'started_at': '2025-06-26T12:43:02.202209Z',
 'upload_id': '754666c3-8394-40cd-b96e-ed05f3385df2'}


Poll the status endpoint until it completes, then inspect the quality of generated answers. distil labs shows four scores to tell you how well the “teacher” model answers your test questions. Think of them as different lenses on the same picture—together they give a fuller view than any single number

| Metric                   | What it really asks                                                                                     | How to read it                                                                                                                                                |
| ------------------------ | ------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Exact-Match (Binary)** | “Did the model give *exactly* the same words as the reference answer?”                                  | 1 = perfect match, 0 = anything else. Great for facts that have one correct phrasing, harsh on synonyms. ([Wikipedia][1])                                     |
| **LLM-as-a-Judge**       | “If we let a large language model act as a human grader, does it say this answer is good?”              | Scores reflect semantic quality even when wording differs; handy when many answers are possible. ([Evidently AI][2], [arXiv][3])                              |
| **ROUGE-L**              | “How much word-overlap is there between answer and reference?” (counts the longest common subsequence). | Higher = more shared wording; favours longer answers that reuse reference phrases. Widely used in text-summarisation tests. ([Wikipedia][4])                  |
| **METEOR**               | “Do the two answers share words *or* close synonyms/stems, and is the wording fluent?”                  | Balances precision + recall, rewards correct synonyms, penalises word-salad; often tracks human judgements better than pure overlap metrics. ([Wikipedia][5]) |

---

##### How to interpret a scorecard

* If Exact-Match is low but LLM-as-a-Judge is high, the answers are probably *right but paraphrased*—consider adding those paraphrases to your reference set.
* If all four numbers sag, revisit your job description or give the model more context; the task may be under-specified.

Follow the links above for deeper dives if you want to explore the math or research behind each metric.

[1]: https://en.wikipedia.org/wiki/Language_model_benchmark "Language model benchmark"
[2]: https://www.evidentlyai.com/llm-guide/llm-as-a-judge "LLM-as-a-judge: a complete guide to using LLMs for evaluations"
[3]: https://arxiv.org/abs/2411.15594 "[2411.15594] A Survey on LLM-as-a-Judge - arXiv"
[4]: https://en.wikipedia.org/wiki/ROUGE_%28metric%29 "ROUGE (metric)"
[5]: https://en.wikipedia.org/wiki/METEOR "METEOR"



In [121]:

from pprint import pprint

response = requests.get(
    f"https://api.distillabs.ai/teacher-evaluations/{teacher_evaluation_id}/status",
    headers=AUTH_HEADER
)
pprint(response.json())


{'evaluation_predictions_download_url': 'https://distil-labs-prod-backend-data.s3.amazonaws.com/teacher-evaluations/92b4881e-1966-4865-9f6e-09a7c328a2b3/output/teacher-evaluation/metrics-eval-full.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAS2VS4EPXLARMAAPV%2F20250626%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20250626T124859Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGUaDGV1LWNlbnRyYWwtMSJIMEYCIQDSUTGhBPBBn4DQ2cfeNwfmBeUyDid1SW46S%2B%2FIHqsTVgIhANICOGlTXDAwINusyTCrBLtz%2BcFCnvyNwALIlawsfpq9Kv0CCF4QABoMMTk0NzIyNDA3NDA2IgydOVQwOb1cMijIerkq2gKmrg2fQXS1cfo9PeHKxIKfs9XlfQahBP6FyP4gQiFcsgTCzATkp3btBhtIRT%2F1W5KZ3SHVIvLe72ewzKJMnFk1tc2pbG2caCma9wB8gEHa8hsgU5WtGUsQnK0RmjsEqRmQYDtXxkhmW7SG8KBmEYgbYRssRgnlulr9zOSuj8PjchqPq%2BlyNN3bocGJPhiuCj8RUp0yTlbVJwTz%2FLkmQIBK5eu4i6p3K%2FhOjGORX8gP%2Buz%2Fok26rmFan2p0CdPejHPAKaKxpvD4VdxvBoiMFhYCKgI3qDQXxWByI%2Ff70yJvkaQ%2FhiEzrcloRZa4Mp862J3pP4hjpln%2BpJg6K%2Bt0ZyGi2h0poeStpkdvvuNnSh8ZTrEtUuEoXb5q8N

### SLM Training
Once the teacher evaluation completes successfully, start the SLM training:

In [22]:
# import time
# from pprint import pprint

# # Start SLM training
# response = requests.post(
#     f"https://api.distillabs.ai/trainings/{upload_id}",
#     headers=AUTH_HEADER,
# )

# pprint(response.json())
# slm_training_job_id = response.json().get("id")
# slm_training_job_id = "3fb0ddda-f2e6-41d0-a927-82dade23763d" # Jacek's
slm_training_job_id = "b65957cb-7ac9-466a-b42e-bf0ca7577d9d"

We can analyze the status of the training job using the `jobs` API. The following code snippets displays the current status of the job we started before. When the job is finished (`status=complete`), we can use the `jobs` API again to get the benchmarking result - the accuracy of the LLM and the accuracy of the fine-tuned SLM. We can achieve this using:

In [28]:
import json
from pprint import pprint

response = requests.get(
    f"https://api.distillabs.ai/trainings/{slm_training_job_id}/status",
    headers=AUTH_HEADER,
)
pprint(response.json())

{'message': '',
 'status': {'dag': 'JOB_SUCCESS',
            'end_time': '2025-06-26T00:03:17.565000Z',
            'logs': '2025-06-25 04:54:48,756\tINFO job_manager.py:531 -- '
                    'Runtime env is setting up.\n'
                    '(evaluate_teacher pid=82555, ip=10.2.4.246) '
                    'INFO:distillib.control.qa.entrypoint:Starting teacher '
                    'evaluation ...\n'
                    '(evaluate_teacher pid=82555, ip=10.2.4.246) '
                    'INFO:absl:Using default tokenizer.\n'
                    '(evaluate_teacher pid=82555, ip=10.2.4.246) [nltk_data] '
                    'Downloading package wordnet to /home/ray/nltk_data...\n'
                    '(evaluate_teacher pid=82555, ip=10.2.4.246) [nltk_data]   '
                    'Package wordnet is already up-to-date!\n'
                    '(evaluate_teacher pid=82555, ip=10.2.4.246) [nltk_data] '
                    'Downloading package punkt_tab to /home/ray/nltk_data...\n'


When the job is finished (`status=complete`), we can use the `jobs` API again to get the benchmarking result for the base and fine-tuned SLM, using the same four metrics as for the teacher evaluation. We can achieve this using:

In [29]:
from pprint import pprint

response = requests.get(
    f"https://api.distillabs.ai/trainings/{slm_training_job_id}/evaluation-results",
    headers=AUTH_HEADER,
)

pprint(response.json())


{'evaluation_results': {'student-base': {'binary': 0.0,
                                         'llm-as-a-judge': 0.3913043478,
                                         'meteor': 0.0965122383,
                                         'rouge': 0.1387747263},
                        'student-tuned': {'binary': 0.0,
                                          'llm-as-a-judge': 0.6304347826,
                                          'meteor': 0.1295266038,
                                          'rouge': 0.1849073846},
                        'teacher': {'binary': 0.0,
                                    'llm-as-a-judge': 0.9782608696,
                                    'meteor': 0.45745125,
                                    'rouge': 0.4737229688}},
 'finetuned_student_evaluation_predictions_download_url': 'https://distil-labs-prod-backend-data.s3.amazonaws.com/trainings/b65957cb-7ac9-466a-b42e-bf0ca7577d9d/finetune_student/output/eval/tuned-model/model-eval/metrics-eval-full.json?X-Am

### Download Your Model
Once training is complete, download your model for deployment.

In [30]:
from pprint import pprint

# Get model download URL
response = requests.get(
    f"https://api.distillabs.ai/trainings/{slm_training_job_id}/model",
    headers=AUTH_HEADER
)

s3url = response.json()["s3_url"]
pprint(response.json())

{'message': 'Found model for training: b65957cb-7ac9-466a-b42e-bf0ca7577d9d',
 's3_url': 'https://distil-labs-prod-backend-data.s3.amazonaws.com/trainings/b65957cb-7ac9-466a-b42e-bf0ca7577d9d/finetune_student/output/model.tar?response-content-disposition=attachment%3B%20filename%20%3D%20b65957cb-7ac9-466a-b42e-bf0ca7577d9d-model.tar&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAS2VS4EPXDDQMFGXM%2F20250626%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20250626T080021Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGAaDGV1LWNlbnRyYWwtMSJHMEUCIEk8gOfCjlMbJ%2BTXfxbwsZ4yFzVPeBupEoI7jU%2FSfnPEAiEA0H73lHdqtcWLxBqLY%2FC1p%2B2%2Bk%2FBfcEVXX3SDvHpoMbcq%2FQIIWRAAGgwxOTQ3MjI0MDc0MDYiDCd6wRbOwURXvuD5KyraArGSu7NBp1vfsgoPQYT%2BpAnN8tC9RZH4FnhM59br4qbPb1gtaqYYG9Zq1v6sT0dYL9Tc%2FM6qmZnMdW73VFyWTrckAi6ERYJpNko%2FSJbMZu%2BopJrmyv2OXJKfsL2yK1AaTkDPp6JoIqngrVzOuRNJ1XZFM6kmtPLotZbiLJx3RNmyPO5eAmJdLcfpp9U%2BsDTRaTIw09YDwo8mb%2B2dEDrGuM9PRYEn9ZfyGsJY07ekTRyHGcCXo%2Bz

In [31]:
import tarfile
import urllib.request

print("Downloading …")
def status(count, block, total):
    print("\r", f"Downloading: {count * block / total:.1%}", end="")


urllib.request.urlretrieve(
    s3url,
    "model.tar",
    reporthook=status,
)

print("\nUnpacking …")
with tarfile.open("model.tar", mode="r:*") as tar:
    tar.extractall(path=".")


 Downloading: 100.0%
Unpacking …


In [32]:
!ls -lt

total 295720
-rw-r--r--  1 maciejgryka staff 293488640 Jun 26 10:00 model.tar
-rw-r--r--  1 maciejgryka staff    347520 Jun 26 10:00 rag-tutorial.ipynb
drwxr-xr-x 13 maciejgryka staff       416 Jun 26 02:00 model
drwxr-xr-x 10 maciejgryka staff       320 Jun 26 01:58 model-adapter
-rw-r--r--  1 maciejgryka staff    393261 Jun 25 15:10 uv.lock
-rw-r--r--  1 maciejgryka staff       609 Jun 25 15:10 pyproject.toml
-rw-r--r--  1 maciejgryka staff       123 Jun 25 14:53 job_ids.json
drwxr-xr-x  7 maciejgryka staff       224 Jun 25 11:14 info
-rw-r--r--  1 maciejgryka staff        90 Jun 25 11:09 hello.py
drwxr-xr-x  6 maciejgryka staff       192 Jun 25 11:04 data
-rw-r--r--  1 maciejgryka staff      1374 Jun 25 11:04 README.md


# Step 3: Build a local RAG system with your fine‑tuned model

Now that we have a small language model fine‑tuned specifically for Roman‑Empire question‑answering, we can build our RAG pipeline around it. This domain‑specialized LLM will provide more accurate, context‑aware answers than our baseline model while still running entirely on local hardware. The main objectives for us are as follows:
  * Launch a lightweight chat model locally with **ollama**.
  * Chunk a Wikipedia article, embed the chunks with **HuggingFace sentence‑transformers**, and store them in an **in‑memory vector store**.
  * Glue retrieval and generation together in a minimal **RAG class**, then test the loop end‑to‑end.

#### Install ollama in your own system

To install ollama, follow the instructions from https://ollama.com/download and make sure to enable the serving daemon (via `ollama serve`). Once ready, make sure the app is running by executing the following command (the list should be empty since we have not loaded any models yet):

In [33]:
! ollama list

NAME                       ID              SIZE      MODIFIED     
model-distillabs:latest    4f777523af55    271 MB    19 hours ago    
llama3.1:latest            f66fc8dc39ea    4.7 GB    9 months ago    


#### (Optional) Install ollama for Google Colab
If you are running this notebook in Google Colab, you can install Ollama using the following link

In [ ]:
! curl -fsSL https://ollama.com/install.sh | sh

Once ollama is installed, we should start the application. You can start the daemon with `ollama serve` using `nohup` to make sure it stays in the background.

In [ ]:
! nohup ollama serve &

Make sure the app is running by executing the following command (the list should be empty since we have not loaded any models yet):

In [ ]:
! ollama list

### Register and test the downloaded model 
Once your model is trained, it should be unpacked and registered with ollama. The downloaded model directory already contains everything that is needed and the model can be registed with the command below. Once it is ready, we can test the model with a standard OpenAI interface

In [34]:
! ollama create model-distillabs -f model/Modelfile

gathering model components ⠙ gathering model components 
copying file sha256:381674853858099b83922844216f3b6bbad44d33cfe8c27076138011c921a04b 100% 
copying file sha256:091520603af37f9b525a81ce9b1193ed200d9af0fb5c0fb357b97e767d0e64bc 100% 
copying file sha256:19118195c7045baadcc67a295f41b47e6820d961119a55a0e39f74a864066977 100% 
copying file sha256:82b84012e3add4d01d12ba14442026e49b8cbbaead1f79ecf3d919784f82dc79 100% 
copying file sha256:ba872b8e416ee4c2c0de3a16324c4601a3120cb5ec03bce40c5237789af0a863 100% 
copying file sha256:e73a059dacdd15d8e4cbdad52a35613ea801bac8a616a7455bee8c10cd400594 100% 
copying file sha256:2b7379f3ae813529281a5c602bc5a11c1d4e0a99107aaa597fe936c1e813ca52 100% 
copying file sha256:9fa311b2bf24b7096356f4f3367af1629a244f201c672a872c61f5015ad3bab9 0% ⠋ gathering model components 
copying file sha256:381674853858099b83922844216f3b6bbad44d33cfe8c27076138011c921a04b 100% 
copying file sha256:091520603af37f9b525a81ce9b1193ed200d9af0fb5c0fb357b97e767d0e64bc 100% 
copyin

In [35]:
from openai import OpenAI

client = OpenAI(
    base_url = 'http://localhost:11434/v1',
    api_key='ollama', # required, but unused
)

response = client.chat.completions.create(
  model="model-distillabs",
  messages=[
    {"role": "user", "content": "What day is it?"},
  ],
)
print(response.choices[0].message.content)

The Sun Thursdays and Friday are the most important dates for many people who believe in the cyclical nature of life. This approach, often called "holidays," emphasizes a more peaceful and uplifting atmosphere than traditional Saturday-to-Sunday or Monday-to-Tuesday rituals. By giving these occasions less emphasis during the main weeks, people consider them as a time to recharge, reflect, and enjoy some peacefulness instead of being stuck in the same routines for too long when they should be focusing their energy on other things like exercising, tending to personal matters, engaging in activities with loved ones, etc.


### Index our target dataset

This section walks through loading the **Wikipedia article on the Roman Empire** into an in‑memory vector store (adapted from [https://python.langchain.com/docs/tutorials/rag/](https://python.langchain.com/docs/tutorials/rag/)):

In [37]:
from langchain_community.document_loaders import WikipediaLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.vectorstores import InMemoryVectorStore

# Split the document into chunks
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
text_splits = text_splitter.split_text(wikipedia_text)
document_splits = text_splitter.create_documents(text_splits)

# Embed and index the chunks
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L12-v2")
vector_store = InMemoryVectorStore(embeddings)
indexed = vector_store.add_documents(documents=document_splits)

### Define the RAG logic

Now that our dataset is indexed and the chat model is live, we can **wire retrieval and generation together**. In this section we implement a bite‑sized `RAG` helper class that

1. fetches the top‑k passages most similar to the user’s question,
2. feeds those passages and the question into the language model via a structured prompt, and
3. returns a concise answer.

With this plumbing in place, answering a question becomes a single‑function call.

In [38]:
from langchain_core.documents import Document
from langchain_openai import ChatOpenAI
from langchain_core.vectorstores import InMemoryVectorStore


class RAG:
    def __init__(self, vector_store: InMemoryVectorStore, llm: ChatOpenAI):
        self.vector_store = vector_store
        self.llm = llm

        self.SYSTEM_PROMPT = """
You are a problem solving model working on task_description XML block:

<task_description>
Answer the question using information from one of the context paragrpahs.
The answer should should contain all important information from the context paragraph but stay short, one sentence maximum.
</task_description>

You will be given a single task with context in the context XML block and the task in the question XML block
Solve the task in question block based on the context in context block.
Generate only the answer, do not generate anything else
"""

        self.PROMPT_TEMPLATE = """
Now for the real task, solve the task in question block based on the context in context block.
Generate only the solution, do not generate anything else.

<context>
{context}
</context>

<question>
{question}
</question>
"""

    def retrieve(self, question: str, k: int = 3):
        return self.vector_store.similarity_search(question, k=k)

    def generate(self, question: str, context_docs):
        context = "\n\n".join(doc.page_content for doc in context_docs)
        messages = [
            {"role": "system", "content": self.SYSTEM_PROMPT},
            {"role": "user", "content": self.PROMPT_TEMPLATE.format(context=context, question=question)},
        ]
        return self.llm.invoke(messages).content

    def answer(self, question: str):
        return self.generate(question, self.retrieve(question))

### Plug the new model into RAG
With the fine‑tuned weights now running locally, the last step is to introduce the specialized LLM into our existing RAG helper class. The retrieval component fetches the most relevant passages about the Roman Empire—while the generation step leverages a model that has been trained on our domain‑specific data.

In [39]:
from langchain_openai import ChatOpenAI

tuned_llm = ChatOpenAI(
    base_url='http://localhost:11434/v1',
    api_key="EMPTY",
    model="model-distillabs",
    temperature=0,
)
tuned_rag = RAG(vector_store=vector_store, llm=tuned_llm)
print(tuned_rag.answer("When did the roman empire collapse?"))

The Roman Empire collapsed in 476 AD, when Romulus Augustulus was forced to abdicate to the Germanic warlord Odoacer. The fall of the Western Roman Empire is not mentioned in the context provided.


### Test our RAG system

In [38]:
sample_qa = [
    {"question": "When did the Roman Empire collapse?", "answer": "The west Roman Empire fell in 476 CE and the Easy laster until the fall of Constantinopol in 1453."},
    {"question": "Who was the first emperor of the Roman Empire?", "answer": "Augustus (formerly Octavian)"},
    {"question": "What were the main languages spoken across the Roman Empire?", "answer": "Latin in the West and Greek in the East"},
    {"question": "What monumental arena in Rome hosted gladiatorial games?", "answer": "The Colosseum"},
]

for qa in sample_qa:
    print(f"Q: {qa['question']}\nA: {qa['answer']}\nP: {tuned_rag.answer(qa['question'])}\n")

Q: When did the Roman Empire collapse?
A: The west Roman Empire fell in 476 CE and the Easy laster until the fall of Constantinopol in 1453.
P: The Roman Empire collapsed in 1453. The Eastern Roman Empire lasted until 1453.

Q: Who was the first emperor of the Roman Empire?
A: Augustus (formerly Octavian)
P: The first emperor of the Roman Empire was Augustus, who ruled from 44 to 14 BCE. He is considered the founder of the Roman Empire and is remembered for his leadership and military conquests.

Q: What were the main languages spoken across the Roman Empire?
A: Latin in the West and Greek in the East
P: Latin and Greek, respectively, were the main languages of the Empire. The Empire was deliberately multilingual, with Latin being the dominant language throughout its history.

Q: What monumental arena in Rome hosted gladiatorial games?
A: The Colosseum
P: The Flavian Amphitheatre, better known as the Colosseum, became the regular arena for blood sports in Rome. The arena was also decor