base:
  task: question-answering-open-book
evaluation:
  num_few_shot_examples: 1
setup:
  student_model_name: meta-llama/Llama-3.1-8B-Instruct
  teacher_model_name: us.meta.llama3-3-70b-instruct-v1:0
synthgen:
  data_generation_strategy: qa-open-book
  generation_target: 10000
tuning:
  num_train_epochs: 32
